### ISSUE TITLE
When the Qc is at No.3 Row 4, it is mistaken for a Qs card. (Every board). Others are still fine.

### ISSUE THREAD

**Issue by Mstumr** [mchung94/solitaire-player#29]
Examples:
![Qs bug](https://user-images.githubusercontent.com/104849582/192816223-718e0fb4-7926-4d3d-b755-84ea1b1071d1.png)
![Qs2 bug](https://user-images.githubusercontent.com/104849582/192818715-26525ca7-a3a3-4e0e-a5a9-9b4c21c01d9f.png)

**Comment by activex88** [comment]
This issue is reproducible. It was caught couple of times. But it may be fixed by recapturing the image of Club Q at the position: row 4 column 3, then recompiled the source code with the newly captured image of Club with the Club Q. 

Hope this will help to solve the problem.

Thanks for your great work!

![image](https://user-images.githubusercontent.com/83848325/212411199-a62983c8-5b85-4f5c-9f3e-fabce1195290.png)

**Comment by mchung94** [comment]
Thanks for finding the issue, the fix, and also for your patience! I pushed out a new release, v2.6.8 here: https://github.com/mchung94/solitaire-player/releases/tag/v2.6.8 which may help.
