### ISSUE TITLE
The Solver error

### ISSUE THREAD

**Issue by Cod3e** [mchung94/solitaire-player#4]
Heya when i tried using the TriPeaks Solver it just threw me a bunch of errors (I do have java) and crashed.
Could ya give me some spider freecell or Klondike Solvers? Or atleast write how to use them. I can provide proof for the errors.

**Comment by mchung94** [comment]
Thanks for the feedback - I'm sorry the solver is giving you errors. I'm still trying to figure out why it doesn't work for some people but it's hard because it works for me. I am trying to figure out a way to redesign this so it's easier to run.

On my computer, I'm using Java JDK 11.0.7 (64-bit) on Windows 10 with the latest updates. Also my monitor is at 100% scale and I'm using the Classic Theme on Microsoft Solitaire Collection. It won't work with other themes or card decks.

I don't have solvers for Spider, FreeCell, or Klondike yet - I'm working on ways to solve these efficiently.

**Comment by Cod3e** [comment]
Either the program can't Figure out am playing tripeaks by language or is it that i use retro cards.
And Thanks for the feedback on Spider KlonDike And Freecell

**Comment by Cod3e** [comment]
So i managed to make it work but it just throws a unknowndeck at me
What to do?

**Comment by Cod3e** [comment]
Same with Pyramid

**Comment by Cod3e** [comment]
Nvm IT has to be windowed and classic. Put that in Readme.

**Comment by mchung94** [comment]
Thanks for the information! I'll update the readme to let everyone else know.
